name: Backend CD
on:
  push:
    branches: [main]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u --${{ secrets.DOCKERHUB_USERNAME }} -p --${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo

      - name: Docker build and push to dev
        if: contains(github.ref, 'dev')
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p {{ secrets.DOCERHUB_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo .
          sh ${{ secrets.DOCKERHUB_USERNAME}}/github-actions-demo
